# Generated by Django 5.1.7 on 2025-03-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('genre', models.CharField(choices=[('AC', 'Acción'), ('CO', 'Comedia'), ('DR', 'Drama'), ('MS', 'Misterio'), ('CS', 'Ciencia Ficción')], max_length=2, verbose_name='Género')),
                ('release_date', models.DateField(verbose_name='Fecha de lanzamiento')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Película',
                'verbose_name_plural': 'Películas',
            },
        ),
    ]
